name: end-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: npm install
      - name: run e2e tests
        uses: cypress-io/github-action@v2
        with:
          start: "npm run start"
          wait-on: "http://localhost:3000"
          config: baseUrl=http://localhost:3000