name: Cypress e2e tests for Vue app
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.x'
      - run: npm install
      - name: run e2e tests
        uses: cypress-io/github-action@v2
        with:
          start: "npm run serve"
          wait-on: "http://localhost:8080"
          config: baseUrl=http://localhost:8080